### ISSUE TITLE
[Muktipath Support] Add new columns in the report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Muktipath#18]
Support ticket- https://avni.freshdesk.com/a/tickets/3076

Jasper report link - [Village visit complete report](https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FMuktipath%2FReports%2FAggregates&reportUnit=%2FMuktipath%2FReports%2FAggregates%2FVillage_complete_report&standAlone=true) 

Recently, couple of new fields were added in the muktipath.reporting_user_field_work_rural  encounter , and these fields value should also come in the above mentioned report

- [x] count(distinct enc.id) when "Did you have an intensive meeting?" = 'Yes' under new column "सघन बैठक"
- [x] count(distinct enc.id) when "Did you have an Safal meeting?"  = 'Yes' under new column "सफल भेट"

**Comment by vedfordev** [comment]
@nupoorkhandelwal 

Added column with mentioned condition please check once and close it.
