### ISSUE TITLE
[Report] Village visits and village programs

### ISSUE THREAD

**Issue by sachsk** [avniproject/Muktipath#7]
Create aggregate report along with line list in jasper

**Filters: date and block**

![5df7c9dd7cf55210dbc8ccbbbfc336fb-4.jpg](https://images.zenhubusercontent.com/5dc4129311dec50001487a46/18c59cc9-3db0-4330-8e9a-d7b66ca3c796)

**Comment by AchalaBelokar** [comment]
Line list for Important village visits Block filter is not working
