### ISSUE TITLE
[Report] Important village visits

### ISSUE THREAD

**Issue by sachsk** [avniproject/Muktipath#8]
Create aggregate report along with line list in jasper

**Filters: date and block**

![5df7c9dd7cf55210dbc8ccbbbfc336fb-5.jpg](https://images.zenhubusercontent.com/5dc4129311dec50001487a46/a7e1e048-3e33-41d2-9941-dbb34d5cd9a6)

**Comment by nupoorkhandelwal** [comment]
Aggregate report--

set role muktipath;

select coalesce("Block", 'Total')                                                                              as "Block",
       count(distinct enc.id)
       filter (where "Reorganised Gram panchayat samiti in the village today?" = 'Yes')                        as "ग्रामपंचायत समितीची बैठक",
       count(distinct enc.id) filter (where "संघटन बैठक झाली का?" = 'हो')                                      as "गाव संघटना बैठक"
        ,
       count(distinct enc.id)
       filter (where "नवीन गाव संघटन स्थ� (653966906)" = 'हो')                                                 as "गावत बैठक घेवुन गाव सांगठना स्थापना झाली",
       count(distinct enc.id)
       filter (where "Did village organisation form in the village?" = 'Yes')                                  as "ग्रामसभा"
        ,
       count(distinct enc.id)
       filter (where "Did non-violence take place in the village today?" = 'Yes')                              as "indicator",
       count(distinct enc.id) filter (where "पंच भेट घेतली का?" = 'हो')                                        as "मुलांचा खेळ आणि शिकण्याचा कार्यक्रम",
       count(distinct enc.id)
       filter (where "Select Program" like '%मुलांचे खेळ व शिक्षण कार्यक्रम%')                                 as "मुलांचा खेळ आणि शिकण्याचा कार्यक्रम",
       count(distinct enc.id) filter (where "गावपातळी व्यसन उप� (667475348)ेतले का?" = 'हो')
                                                                                                               as "गाव पाटडी क्लिनिक",

       count(distinct enc.id) filter (where "Reorganised Gram panchayat samiti in the village today?" = 'Yes') +
       count(distinct enc.id) filter (where "संघटन बैठक झाली का?" = 'हो') +
       count(distinct enc.id) filter (where "नवीन गाव संघटन स्थ� (653966906)" = 'हो') +
       count(distinct enc.id) filter (where "Did village organisation form in the village?" = 'Yes') +
       count(distinct enc.id) filter (where "पंच भेट घेतली का?" = 'हो') +
       count(distinct enc.id) filter (where "Select Program" like '%मुलांचे खेळ व शिक्षण कार्यक्रम%') +
       count(distinct enc.id)
       filter (where "गावपातळी व्यसन उप� (667475348)ेतले का?" = 'हो')                                          as "Total"

from muktipath.reporting_user_field_work_rural enc
         left join muktipath.address on address.id = enc.address_id
group by rollup ("Block");

select reporting_user.first_name,
       "District",
       "Block",
       encounter_date_time::date,
       "Reorganised Gram panchayat samiti in the village today?",
       "किती महिला निवडल्या",
       "किती पुरुष निवडले",
       "नवीन संघटनेचा फोटो",
       "Status of village information",
       "गावपातळी व्यसन उप� (667475348)" as "गावपातळी व्यसन उपचार शिबीर घेतले का?",
       "संघटन बैठक झाली का?",
       "No of people in the village who drink alcohol con (1116649124)" as "No of people in the village who drink alcohol continuously for 8-10 days?",
       "Is alcohol brewed for domestic work in the village?",
       "Photo of the registration register for this Gram  (1396394347)" as "Photo of the registration register for this Gram Panchayat Samiti meeting",
       "How many villages come under this Gram Panchayat?",
       "Was the Chairman present in this Gram Panchayat C (1615928178)" as "Was the Chairman present in this Gram Panchayat Committee meeting?",
       "photo",
       "काय ठरले या बैठकी मध्ये",
       "name of school",
       "मुले -मुली उपस्थित  (330474120)" as "मुले -मुली उपस्थित होते तो आकडा टाका",
       "Name of panch",
       "number of panch",
       "ज्यांच्या घरी मुक� (2006207684)" as "ज्यांच्या घरी मुक्काम केला त्यांचे नाव लिहा",
       "कोणत्या विषयावर च� (2115317960)" as "कोणत्या विषयावर चर्चा झाली",
       "मोबाइल नंबर टाका",
       "What non-violent activity has been done against t (1447929581)" as "What non-violent activity has been done against this tobacco seller",
       "How many people were involved in this action",
       "Alcohol destroyed  Amount",
       "How many people were involved in this action-tobacco",
       "जनजागृती  कार्यक्रम",
       "village",
       "रात्री मुक्काम केला का?",
       "नवीन संघटन कृती",
       "गाव भेट ज्या दिवशी  (961624986)" as "गाव भेट ज्या दिवशी केली त्या दिवसाची तारीख निवडा",
       "Did non-violence take place in the village today?",
       "पंच भेट घेतली का?",
       "शाळेत शाळा कार्यक� (1442632479)" as "शाळेत शाळा कार्यक्रम घेतला का?",
       "नवीन गाव संघटन स्थ� (653966906)" as "नवीन गाव संघटन स्थापन झाले का?",
       "तालुका क्लिनिक सा� (1980424657)" as "तालुका क्लिनिक साठी नवीन पेशंट रेफर केले का?",
       "How many places in the village make liquor?",
       "No of places in village where tobacco product solds?",
       "How many places in the village sell liquor?",
       "Total number of panthelas in the village",
       "Is village panchayat committee formed in village?",
       "Did village organisation form in the village?",
       "Has the village passed a resolution banning alcohol?",
       "Name of liquor dealer for this activity happened",
       "किती सदस्य उपस्थित होते",
       "Reason of non-violent activity",
       "What non-violent activity has been done",
       "Did the information of the decision taken in the  (1841421957)" as "Did the information of the decision taken in the Gram Panchayat Samiti be posted on the wall elsewhere in the village?",
       "Gram Panchayat Samiti meeting photo",
       "How many members were present in this Gram pancha (1840443748)" as "How many members were present in this Gram panchayat samiti meeting?",
       "What did this committee do after the election today?",
       "ठरलेल्या ठरवाच्या (1952399644)" as "ठरलेल्या ठरवाच्या रजिस्टर/मिनिट्स चा फोटो जोडा",
       "school program photo",
       "केस बद्दलची सर्व म� (449827481)" as "केस बद्दलची सर्व माहिती पंच यांना दिली का ?",
       "नवीन किती पेशंट रे� (406968110)" as "नवीन किती पेशंट रेफर केले",
       "Select Program",
       "प्रमुख व्यक्तीचे � (852374501)" as "प्रमुख व्यक्तीचे नाव लिहा",
       "महत्वाच्या कार्यक (766325280)" as "महत्वाच्या कार्यक्रम चा एक फोटो जोडा",
       "Name of the tobacco seller for this activity is happened",
       "Photo of non-violent action or seized goods",
       "Tobaco destroyed amount",
       "Photo of non-violent action or seized goods-tobacco",
       "पूर्ण वेळ उपचार  घे (269462001)" as "पूर्ण वेळ उपचार घेतलेले पेशंट",
       "Mobile Number",
       "सोबत",
       "कार्यकर्ता  नाव"
from muktipath.reporting_user_field_work_rural enc
                  left join muktipath.address on address.id = enc.address_id
                  left join muktipath.reporting_user on reporting_user.id = enc.individual_id
where reporting_user.is_voided = false and enc.is_voided = false ;
